In [ ]:
from evidently.model_profile import Profile
from evidently.model_profile.sections import DataDriftProfileSection, CatTargetDriftProfileSection

:

In [62]:
import pandas as pd
import numpy as np
import json

In [63]:
filename = "target_drift_dataset.csv"
df = pd.read_csv(filename)

In [64]:
new_data_path = "target_drift_test_dataset.csv"
df_new_data = pd.read_csv(new_data_path)

In [65]:
len(df), len(df_new_data)

(61445, 15238)

In [66]:
df_new_data.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       ...
       '762', '763', '764', '765', '766', '767', 'project_id', 'entry_id',
       'excerpt', 'target'],
      dtype='object', length=773)

In [67]:
df.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       ...
       '762', '763', '764', '765', '766', '767', 'project_id', 'entry_id',
       'excerpt', 'target'],
      dtype='object', length=773)

In [68]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [69]:
len(df)

61445

In [70]:
df.head(2)

,0,1,2,3,4,5,6,7,8,9,...,762,763,764,765,766,767,project_id,entry_id,excerpt,target
0,-0.125759,0.011437,0.034063,0.100342,0.24212,-0.027853,0.145363,-0.16995,0.007012,0.107553,...,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,2225.0,489433,Primary and secondary net enrollment rates are...,Education
1,-0.125759,0.011437,0.034063,0.100342,0.24212,-0.027853,0.145363,-0.16995,0.007012,0.107553,...,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,2225.0,489433,Primary and secondary net enrollment rates are...,Context->Socio Cultural

In [71]:
df["project_id"].unique()

array([2225., 2170., 1183., 2311., 2028., 2098., 2099., 2335., 2334.,
       2336., 2331.])

In [72]:
def use_mask_project_id_based(df, project_id=None):
    if project_id:
        mask = df["project_id"] == project_id
    
    df_masked = df[mask]
    return df_masked

In [73]:
drift_profile = Profile(sections=[CatTargetDriftProfileSection()])

In [38]:
df_reference_2225 = use_mask_project_id_based(df, project_id=2225.0)

In [39]:
df_reference_2225 = df_reference_2225.drop(["project_id", "entry_id", "excerpt"], axis=1)

In [40]:
df_reference_2225

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,target
0,-0.125759,0.011437,0.034063,0.100342,0.242120,-0.027853,0.145363,-0.169950,0.007012,0.107553,...,-0.092254,0.100884,-0.170843,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,Education
1,-0.125759,0.011437,0.034063,0.100342,0.242120,-0.027853,0.145363,-0.169950,0.007012,0.107553,...,-0.092254,0.100884,-0.170843,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,Context->Socio Cultural
2,-0.125759,0.011437,0.034063,0.100342,0.242120,-0.027853,0.145363,-0.169950,0.007012,0.107553,...,-0.092254,0.100884,-0.170843,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,Humanitarian Conditions->Living Standards
3,-0.026215,0.054579,0.017312,-0.009798,0.454802,0.034562,0.187084,0.065339,0.102508,0.243132,...,-0.112998,0.048827,0.059336,-0.025251,0.061632,0.039132,0.116198,0.080575,-0.013603,Education
4,-0.026215,0.054579,0.017312,-0.009798,0.454802,0.034562,0.187084,0.065339,0.102508,0.243132,...,-0.112998,0.048827,0.059336,-0.025251,0.061632,0.039132,0.116198,0.080575,-0.013603,Context->Socio Cultural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35041,-0.009236,0.034208,0.050378,0.011745,1.010702,-0.063892,0.071482,-0.068059,-0.012831,0.178525,...,-0.032242,0.087459,-0.102677,-0.022230,0.127030,-0.079322,-0.047792,0.163077,0.031407,Food Security
35042,-0.009236,0.034208,0.050378,0.011745,1.010702,-0.063892,0.071482,-0.068059,-0.012831,0.178525,...,-0.032242,0.087459,-0.102677,-0.022230,0.127030,-0.079322,-0.047792,0.163077,0.031407,Impact->Driver/Aggravating Factors
35047,-0.014236,0.022273,0.048252,-0.039590,0.664223,-0.119761,0.071215,-0.056716,-0.009074,0.159224,...,-0.019108,0.084813,-0.081457,0.010761,0.154140,-0.072042,-0.059422,0.240164,0.052027,Agriculture
35048,-0.014236,0.022273,0.048252,-0.039590,0.664223,-0.119761,0.071215,-0.056716,-0.009074,0.159224,...,-0.019108,0.084813,-0.081457,0.010761,0.154140,-0.072042,-0.059422,0.240164,0.052027,Food Security
35049,-0.014236,0.022273,0.048252,-0.039590,0.664223,-0.119761,0.071215,-0.056716,-0.009074,0.159224,...,-0.019108,0.084813,-0.081457,0.010761,0.154140,-0.072042,-0.059422,0.240164,0.052027,Impact->Driver/Aggravating Factors

In [41]:
df_prod_data_2170 = use_mask_project_id_based(df, project_id=2225.0)

In [42]:
df_prod_data_2170 = df_prod_data_2170.drop(["project_id", "entry_id", "excerpt"], axis=1)

In [43]:
df_prod_data_2170

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,target
0,-0.125759,0.011437,0.034063,0.100342,0.242120,-0.027853,0.145363,-0.169950,0.007012,0.107553,...,-0.092254,0.100884,-0.170843,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,Education
1,-0.125759,0.011437,0.034063,0.100342,0.242120,-0.027853,0.145363,-0.169950,0.007012,0.107553,...,-0.092254,0.100884,-0.170843,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,Context->Socio Cultural
2,-0.125759,0.011437,0.034063,0.100342,0.242120,-0.027853,0.145363,-0.169950,0.007012,0.107553,...,-0.092254,0.100884,-0.170843,-0.057174,-0.013843,0.093444,0.239364,-0.054875,-0.185147,Humanitarian Conditions->Living Standards
3,-0.026215,0.054579,0.017312,-0.009798,0.454802,0.034562,0.187084,0.065339,0.102508,0.243132,...,-0.112998,0.048827,0.059336,-0.025251,0.061632,0.039132,0.116198,0.080575,-0.013603,Education
4,-0.026215,0.054579,0.017312,-0.009798,0.454802,0.034562,0.187084,0.065339,0.102508,0.243132,...,-0.112998,0.048827,0.059336,-0.025251,0.061632,0.039132,0.116198,0.080575,-0.013603,Context->Socio Cultural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35041,-0.009236,0.034208,0.050378,0.011745,1.010702,-0.063892,0.071482,-0.068059,-0.012831,0.178525,...,-0.032242,0.087459,-0.102677,-0.022230,0.127030,-0.079322,-0.047792,0.163077,0.031407,Food Security
35042,-0.009236,0.034208,0.050378,0.011745,1.010702,-0.063892,0.071482,-0.068059,-0.012831,0.178525,...,-0.032242,0.087459,-0.102677,-0.022230,0.127030,-0.079322,-0.047792,0.163077,0.031407,Impact->Driver/Aggravating Factors
35047,-0.014236,0.022273,0.048252,-0.039590,0.664223,-0.119761,0.071215,-0.056716,-0.009074,0.159224,...,-0.019108,0.084813,-0.081457,0.010761,0.154140,-0.072042,-0.059422,0.240164,0.052027,Agriculture
35048,-0.014236,0.022273,0.048252,-0.039590,0.664223,-0.119761,0.071215,-0.056716,-0.009074,0.159224,...,-0.019108,0.084813,-0.081457,0.010761,0.154140,-0.072042,-0.059422,0.240164,0.052027,Food Security
35049,-0.014236,0.022273,0.048252,-0.039590,0.664223,-0.119761,0.071215,-0.056716,-0.009074,0.159224,...,-0.019108,0.084813,-0.081457,0.010761,0.154140,-0.072042,-0.059422,0.240164,0.052027,Impact->Driver/Aggravating Factors

In [44]:
reference_df = df_reference_2225
prod_df = df_prod_data_2170

In [46]:
drift_profile.calculate(reference_df, prod_df, column_mapping=None)

In [47]:
drift_profile_json = json.loads(drift_profile.json())

In [48]:
target_drift = drift_profile_json["cat_target_drift"]["data"]["metrics"]["target_drift"]

In [49]:
target_drift

0.0

In [51]:
drift_profile = Profile(sections=[CatTargetDriftProfileSection()])

In [52]:
df.project_id.unique()

array([2225., 2170., 1183., 2311., 2028., 2098., 2099., 2335., 2334.,
       2336., 2331.])

In [91]:
results = []

In [92]:
for ref_project_id in df.project_id.unique():
    for prod_project_id in df_new_data.project_id.unique():
        if ref_project_id == prod_project_id:
            df_reference = use_mask_project_id_based(df, project_id=ref_project_id)
            df_reference = df_reference.drop(["project_id", "entry_id", "excerpt"], axis=1)
            df_prod = use_mask_project_id_based(df_new_data, project_id=prod_project_id)
            df_prod = df_prod.drop(["project_id", "entry_id", "excerpt"], axis=1)

            drift_profile.calculate(df_reference, df_prod, column_mapping=None)
            drift_profile_json = json.loads(drift_profile.json())
            target_drift = drift_profile_json["cat_target_drift"]["data"]["metrics"]["target_drift"]

            results.append({
                "reference_project_id": ref_project_id,
                "prod_project_id": prod_project_id,
                "target_drift": target_drift
            })

In [93]:
results_df = pd.DataFrame.from_records(results)

In [94]:
results_df

   reference_project_id  prod_project_id  target_drift
0                2225.0           2225.0      0.122392
1                2170.0           2170.0      0.088409
2                2311.0           2311.0      0.106322
3                2028.0           2028.0      0.073818
4                2098.0           2098.0      0.195527
5                2099.0           2099.0      0.128003